### ISSUE TITLE
启用VPN时禁用代理，断开VPN后没有自动恢复内置代理

### ISSUE THREAD

**Issue by lbroot** [NekogramX/NekoX#59]
**Describe the bug**
#bug 您好，刚刚有发现开启**“启用VPN时禁用代理”**后，若断开系统VPN，内置代理不会自动重新连接，希望修复。

**Smartphone (please complete the following information):**
 - OS: [Android 7.0]
 - Version [5.15.0]

**Comment by nekohasekai** [comment]
确实没这个功能，你可以当做特性。
