### ISSUE TITLE
Open source blobs

### ISSUE THREAD

**Issue by proletarius101** [NekogramX/NekoX#80]
**Is your feature request related to a problem? Please describe.**

Firstly I do appreciate your work here. But I notice that there are some blobs introduced by 48b2e1f47c, such as https://github.com/NekogramX/NekoX/blob/48b2e1f47c5db5129039a262bbde2aa6b10d3fae/TMessagesProj/libs/libv2ray.aar. 

Although I understand that their usage is obvious from their name. However, as we know it's always not a good idea to have such blobs in an open source software, especially when it has sensitive usage.

**Describe the solution you'd like**
Open source how such blobs are generated. Maybe open source the script or generate it via CI.

**Describe alternatives you've considered**
At least it should be elaborate that where they come from.

**Additional context**

**Comment by nekohasekai** [comment]
It compiles from github.com/2dust/AndroidLibV2rayLite
  Health, specifically [here](https://github.com/NekogramX/NekoX/blob/master/.github/workflows/foss.yml)

**Comment by xcffl** [comment]
Great to hear that!

**Comment by proletarius101** [comment]
Thanks :)
